### ISSUE TITLE
Where is the subtitle stores or how can I save extracted subs as srt/vtt? Thank you very much.

### ISSUE THREAD

**Issue by suliveevil** [agzam/youtube-sub-extractor.el#14]

**Comment by suliveevil** [comment]
Emacs newbie here, sorry for bothering. 😬

**Comment by agzam** [comment]
Oh, I never thought about keeping the files. Currently it simply deletes the sub file. Do you need to save them often? For now, maybe you can simply replace this sexp here https://github.com/agzam/youtube-sub-extractor.el/blob/main/youtube-sub-extractor.el#L342 with 
`(message fpath)` and get to the file that way.

I'll consider implementing a flag for keeping the sub file.

**Comment by suliveevil** [comment]
That would be great!

English is my second language, sometimes I want to translate subtitles into my mother language.
